package nesemulator.cpu;

import java.util.HashMap;

public enum Opcode {

    BRK(0x00, "BRK", AddressingMode.IMPLIED),
    ORA_INDIRECT_X(0x01, "ORA", AddressingMode.INDIRECT_X),
    STP_02(0x02, "STP", AddressingMode.IMPLIED),
    SLO_INDIRECT_X(0x03, "SLO", AddressingMode.INDIRECT_X),
    NOP_ZERO_PAGE(0x04, "NOP", AddressingMode.ZERO_PAGE),
    ORA_ZERO_PAGE(0x05, "ORA", AddressingMode.ZERO_PAGE),
    ASL_ZERO_PAGE(0x06, "ASL", AddressingMode.ZERO_PAGE),
    SLO_ZERO_PAGE(0x07, "SLO", AddressingMode.ZERO_PAGE),
    PHP(0x08, "PHP", AddressingMode.IMPLIED),
    ORA_IMMEDIATE(0x09, "ORA", AddressingMode.IMMEDIATE),
    ASL_ACCUMULATOR(0x0A, "ASL", AddressingMode.ACCUMULATOR),
    ANC_IMMEDIATE_0B(0x0B, "ANC", AddressingMode.IMMEDIATE),
    NOP_ABSOLUTE(0x0C, "NOP", AddressingMode.ABSOLUTE),
    ORA_ABSOLUTE(0x0D, "ORA", AddressingMode.ABSOLUTE),
    ASL_ABSOLUTE(0x0E, "ASL", AddressingMode.ABSOLUTE),
    SLO_ABSOLUTE(0x0F, "SLO", AddressingMode.ABSOLUTE),

    BPL(0x10, "BPL", AddressingMode.RELATIVE),
    ORA_INDIRECT_Y(0x11, "ORA", AddressingMode.INDIRECT_Y),
    STP_12(0x12, "STP", AddressingMode.IMPLIED),
    SLO_INDIRECT_Y(0x13, "SLO", AddressingMode.INDIRECT_Y),
    NOP_ZERO_PAGE_X_14(0x14, "NOP", AddressingMode.ZERO_PAGE_X),
    ORA_ZERO_PAGE_X(0x15, "ORA", AddressingMode.ZERO_PAGE_X),
    ASL_ZERO_PAGE_X(0x16, "ASL", AddressingMode.ZERO_PAGE_X),
    SLO_ZERO_PAGE_X(0x17, "SLO", AddressingMode.ZERO_PAGE_X),
    CLC(0x18, "CLC", AddressingMode.IMPLIED),
    ORA_ABSOLUTE_Y(0x19, "ORA", AddressingMode.ABSOLUTE_Y),
    NOP_1A(0x1A, "NOP", AddressingMode.IMPLIED),
    SLO_ABSOLUTE_Y(0x1B, "SLO", AddressingMode.ABSOLUTE_Y),
    NOP_ABSOLUTE_X_1C(0x1C, "NOP", AddressingMode.ABSOLUTE_X),
    ORA_ABSOLUTE_X(0x1D, "ORA", AddressingMode.ABSOLUTE_X),
    ASL_ABSOLUTE_X(0x1E, "ASL", AddressingMode.ABSOLUTE_X),
    SLO_ABSOLUTE_X(0x1F, "SLO", AddressingMode.ABSOLUTE_X),

    JSR(0x20, "JSR", AddressingMode.ABSOLUTE),
    AND_INDIRECT_X(0x21, "AND", AddressingMode.INDIRECT_X),
    STP_22(0x22, "STP", AddressingMode.IMPLIED),
    RLA_INDIRECT_X(0x23, "RLA", AddressingMode.INDIRECT_X),
    BIT_ZERO_PAGE(0x24, "BIT", AddressingMode.ZERO_PAGE),
    AND_ZERO_PAGE(0x25, "AND", AddressingMode.ZERO_PAGE),
    ROL_ZERO_PAGE(0x26, "ROL", AddressingMode.ZERO_PAGE),
    RLA_ZERO_PAGE(0x27, "RLA", AddressingMode.ZERO_PAGE),
    PLP(0x28, "PLP", AddressingMode.IMPLIED),
    AND_IMMEDIATE(0x29, "AND", AddressingMode.IMMEDIATE),
    ROL_ACCUMULATOR(0x2A, "ROL", AddressingMode.ACCUMULATOR),
    ANC_IMMEDIATE_2B(0x2B, "ANC", AddressingMode.IMMEDIATE),
    BIT_ABSOLUTE(0x2C, "BIT", AddressingMode.ABSOLUTE),
    AND_ABSOLUTE(0x2D, "AND", AddressingMode.ABSOLUTE),
    ROL_ABSOLUTE(0x2E, "ROL", AddressingMode.ABSOLUTE),
    RLA_ABSOLUTE(0x2F, "RLA", AddressingMode.ABSOLUTE),

    BMI(0x30, "BMI", AddressingMode.RELATIVE),
    AND_INDIRECT_Y(0x31, "AND", AddressingMode.INDIRECT_Y),
    STP_32(0x32, "STP", AddressingMode.IMPLIED),
    RLA_INDIRECT_Y(0x33, "RLA", AddressingMode.INDIRECT_Y),
    NOP_ZERO_PAGE_X_34(0x34, "NOP", AddressingMode.ZERO_PAGE_X),
    AND_ZERO_PAGE_X(0x35, "AND", AddressingMode.ZERO_PAGE_X),
    ROL_ZERO_PAGE_X(0x36, "ROL", AddressingMode.ZERO_PAGE_X),
    RLA_ZERO_PAGE_X(0x37, "RLA", AddressingMode.ZERO_PAGE_X),
    SEC(0x38, "SEC", AddressingMode.IMPLIED),
    AND_ABSOLUTE_Y(0x39, "AND", AddressingMode.ABSOLUTE_Y),
    NOP_3A(0x3A, "NOP", AddressingMode.IMPLIED),
    RLA_ABSOLUTE_Y(0x3B, "RLA", AddressingMode.ABSOLUTE_Y),
    NOP_ABSOLUTE_X_3C(0x3C, "NOP", AddressingMode.ABSOLUTE_X),
    AND_ABSOLUTE_X(0x3D, "AND", AddressingMode.ABSOLUTE_X),
    ROL_ABSOLUTE_X(0x3E, "ROL", AddressingMode.ABSOLUTE_X),
    RLA_ABSOLUTE_X(0x3F, "RLA", AddressingMode.ABSOLUTE_X),

    RTI(0x40, "RTI", AddressingMode.IMPLIED),
    EOR_INDIRECT_X(0x41, "EOR", AddressingMode.INDIRECT_X),
    STP_42(0x42, "STP", AddressingMode.IMPLIED),
    SRE_INDIRECT_X(0x43, "SRE", AddressingMode.INDIRECT_X),
    NOP_ZERO_PAGE_44(0x44, "NOP", AddressingMode.ZERO_PAGE),
    EOR_ZERO_PAGE(0x45, "EOR", AddressingMode.ZERO_PAGE),
    LSR_ZERO_PAGE(0x46, "LSR", AddressingMode.ZERO_PAGE),
    SRE_ZERO_PAGE(0x47, "SRE", AddressingMode.ZERO_PAGE),
    PHA(0x48, "PHA", AddressingMode.IMPLIED),
    EOR_IMMEDIATE(0x49, "EOR", AddressingMode.IMMEDIATE),
    LSR_ACCUMULATOR(0x4A, "LSR", AddressingMode.ACCUMULATOR),
    ALR_IMMEDIATE(0x4B, "ALR", AddressingMode.IMMEDIATE),
    JMP_ABSOLUTE(0x4C, "JMP", AddressingMode.ABSOLUTE),
    EOR_ABSOLUTE(0x4D, "EOR", AddressingMode.ABSOLUTE),
    LSR_ABSOLUTE(0x4E, "LSR", AddressingMode.ABSOLUTE),
    SRE_ABSOLUTE(0x4F, "SRE", AddressingMode.ABSOLUTE),

    BVC(0x50, "BVC", AddressingMode.RELATIVE),
    EOR_INDIRECT_Y(0x51, "EOR", AddressingMode.INDIRECT_Y),
    STP_52(0x52, "STP", AddressingMode.IMPLIED),
    SRE_INDIRECT_Y(0x53, "SRE", AddressingMode.INDIRECT_Y),
    NOP_ZERO_PAGE_X_54(0x54, "NOP", AddressingMode.ZERO_PAGE_X),
    EOR_ZERO_PAGE_X(0x55, "EOR", AddressingMode.ZERO_PAGE_X),
    LSR_ZERO_PAGE_X(0x56, "LSR", AddressingMode.ZERO_PAGE_X),
    SRE_ZERO_PAGE_X(0x57, "SRE", AddressingMode.ZERO_PAGE_X),
    CLI(0x58, "CLI", AddressingMode.IMPLIED),
    EOR_ABSOLUTE_Y(0x59, "EOR", AddressingMode.ABSOLUTE_Y),
    NOP_5A(0x5A, "NOP", AddressingMode.IMPLIED),
    SRE_ABSOLUTE_Y(0x5B, "SRE", AddressingMode.ABSOLUTE_Y),
    NOP_ABSOLUTE_X_5C(0x5C, "NOP", AddressingMode.ABSOLUTE_X),
    EOR_ABSOLUTE_X(0x5D, "EOR", AddressingMode.ABSOLUTE_X),
    LSR_ABSOLUTE_X(0x5E, "LSR", AddressingMode.ABSOLUTE_X),
    SRE_ABSOLUTE_X(0x5F, "SRE", AddressingMode.ABSOLUTE_X),

    RTS(0x60, "RTS", AddressingMode.IMPLIED),
    ADC_INDIRECT_X(0x61, "ADC", AddressingMode.INDIRECT_X),
    STP_62(0x62, "STP", AddressingMode.IMPLIED),
    RRA_INDIRECT_X(0x63, "RRA", AddressingMode.INDIRECT_X),
    NOP_ZERO_PAGE_64(0x64, "NOP", AddressingMode.ZERO_PAGE),
    ADC_ZERO_PAGE(0x65, "ADC", AddressingMode.ZERO_PAGE),
    ROR_ZERO_PAGE(0x66, "ROR", AddressingMode.ZERO_PAGE),
    RRA_ZERO_PAGE(0x67, "RRA", AddressingMode.ZERO_PAGE),
    PLA(0x68, "PLA", AddressingMode.IMPLIED),
    ADC_IMMEDIATE(0x69, "ADC", AddressingMode.IMMEDIATE),
    ROR(0x6A, "ROR", AddressingMode.IMPLIED),
    ARR_IMMEDIATE(0x6B, "ARR", AddressingMode.IMMEDIATE),
    JMP_INDIRECT(0x6C, "JMP", AddressingMode.INDIRECT),
    ADC_ABSOLUTE(0x6D, "ADC", AddressingMode.ABSOLUTE),
    ROR_ABSOLUTE(0x6E, "ROR", AddressingMode.ABSOLUTE),
    RRA_ABSOLUTE(0x6F, "RRA", AddressingMode.ABSOLUTE),

    BVS(0x70, "BVS", AddressingMode.RELATIVE),
    ADC_INDIRECT_Y(0x71, "ADC", AddressingMode.INDIRECT_Y),
    STP_72(0x72, "STP", AddressingMode.IMPLIED),
    RRA_INDIRECT_Y(0x73, "RRA", AddressingMode.INDIRECT_Y),
    NOP_ZERO_PAGE_X_74(0x74, "NOP", AddressingMode.ZERO_PAGE_X),
    ADC_ZERO_PAGE_X(0x75, "ADC", AddressingMode.ZERO_PAGE_X),
    ROR_ZERO_PAGE_X(0x76, "ROR", AddressingMode.ZERO_PAGE_X),
    RRA_ZERO_PAGE_X(0x77, "RRA", AddressingMode.ZERO_PAGE_X),
    SEI(0x78, "SEI", AddressingMode.IMPLIED),
    ADC_ABSOLUTE_Y(0x79, "ADC", AddressingMode.ABSOLUTE_Y),
    NOP_7A(0x7A, "NOP", AddressingMode.IMPLIED),
    RRA_ABSOLUTE_Y(0x7B, "RRA", AddressingMode.ABSOLUTE_Y),
    NOP_ABSOLUTE_X_7C(0x7C, "NOP", AddressingMode.ABSOLUTE_X),
    ADC_ABSOLUTE_X(0x7D, "ADC", AddressingMode.ABSOLUTE_X),
    ROR_ABSOLUTE_X(0x7E, "ROR", AddressingMode.ABSOLUTE_X),
    RRA_ABSOLUTE_X(0x7F, "RRA", AddressingMode.ABSOLUTE_X),

    NOP_IMMEDIATE_80(0x80, "NOP", AddressingMode.IMMEDIATE),
    STA_INDIRECT_X(0x81, "STA", AddressingMode.INDIRECT_X),
    NOP_IMMEDIATE_82(0x82, "NOP", AddressingMode.IMMEDIATE),
    SAX_INDIRECT_X(0x83, "SAX", AddressingMode.INDIRECT_X),
    STY_ZERO_PAGE(0x84, "STY", AddressingMode.ZERO_PAGE),
    STA_ZERO_PAGE(0x85, "STA", AddressingMode.ZERO_PAGE),
    STX_ZERO_PAGE(0x86, "STX", AddressingMode.ZERO_PAGE),
    SAZ_ZERO_PAGE(0x87, "SAX", AddressingMode.ZERO_PAGE),
    DEY(0x88, "DEY", AddressingMode.IMPLIED),
    NOP_IMMEDIATE_89(0x89, "NOP", AddressingMode.IMMEDIATE),
    TXA(0x8A, "TXA", AddressingMode.IMPLIED),
    XAA_IMMEDIATE(0x8B, "XAA", AddressingMode.IMMEDIATE),
    STY_ABSOLUTE(0x8C, "STY", AddressingMode.ABSOLUTE),
    STA_ABSOLUTE(0x8D, "STA", AddressingMode.ABSOLUTE),
    STX_ABSOLUTE(0x8E, "STX", AddressingMode.ABSOLUTE),
    SAX_ABSOLUTE(0x8F, "SAX", AddressingMode.ABSOLUTE),

    BCC(0x90, "BCC", AddressingMode.RELATIVE),
    STA_INDIRECT_Y(0x91, "STA", AddressingMode.INDIRECT_Y),
    STP_92(0x92, "STP", AddressingMode.IMPLIED),
    AHX_INDIRECT_Y(0x93, "AHX", AddressingMode.INDIRECT_Y),
    STY_ZERO_PAGE_X(0x94, "STY", AddressingMode.ZERO_PAGE_X),
    STA_ZERO_PAGE_X(0x95, "STA", AddressingMode.ZERO_PAGE_X),
    STX_ZERO_PAGE_Y(0x96, "STX", AddressingMode.ZERO_PAGE_Y),
    SAX_ZERO_PAGE_Y(0x97, "SAX", AddressingMode.ZERO_PAGE_Y),
    TYA(0x98, "TYA", AddressingMode.IMPLIED),
    STA_ABSOLUTE_Y(0x99, "STA", AddressingMode.ABSOLUTE_Y),
    TXS(0x9A, "TXS", AddressingMode.IMPLIED),
    TAS_ABSOLUTE_Y(0x9B, "TAS", AddressingMode.ABSOLUTE_Y),
    SHY_ABSOLUTE_X(0x9C, "SHY", AddressingMode.ABSOLUTE_X),
    STA_ABSOLUTE_X(0x9D, "STA", AddressingMode.ABSOLUTE_X),
    SHX_ABSOLUTE_Y(0x9E, "SHX", AddressingMode.ABSOLUTE_Y),
    AHX_ABSOLUTE_Y(0x9F, "AHX", AddressingMode.ABSOLUTE_Y),

    LDY_IMMEDIATE(0xA0, "LDY", AddressingMode.IMMEDIATE),
    LDA_INDIRECT_X(0xA1, "LDA", AddressingMode.INDIRECT_X),
    LDX_IMMEDIATE(0xA2, "LDX", AddressingMode.IMMEDIATE),
    LAX_INDIRECT_X(0xA3, "LAX", AddressingMode.INDIRECT_X),
    LDY_ZERO_PAGE(0xA4, "LDY", AddressingMode.ZERO_PAGE),
    LDA_ZERO_PAGE(0xA5, "LDA", AddressingMode.ZERO_PAGE),
    LDX_ZERO_PAGE(0xA6, "LDX", AddressingMode.ZERO_PAGE),
    LAX_ZERO_PAGE(0xA7, "LAX", AddressingMode.ZERO_PAGE),
    TAY(0xA8, "TAY", AddressingMode.IMPLIED),
    LDA_IMMEDIATE(0xA9, "LDA", AddressingMode.IMMEDIATE),
    TAX(0xAA, "TAX", AddressingMode.IMPLIED),
    LAX_IMMEDIATE(0xAB, "LAX", AddressingMode.IMMEDIATE),
    LDY_ABSOLUTE(0xAC, "LDY", AddressingMode.ABSOLUTE),
    LDA_ABSOLUTE(0xAD, "LDA", AddressingMode.ABSOLUTE),
    LDX_ABSOLUTE(0xAE, "LDX", AddressingMode.ABSOLUTE),
    LAX_ABSOLUTE(0xAF, "LAX", AddressingMode.ABSOLUTE),

    BCS(0xB0, "BCS", AddressingMode.RELATIVE),
    LDA_INDIRECT_Y(0xB1, "LDA", AddressingMode.INDIRECT_Y),
    STP_B2(0xB2, "STP", AddressingMode.IMPLIED),
    LAX_INDIRECT_Y(0xB3, "LAX", AddressingMode.INDIRECT_Y),
    LDY_ZERO_PAGE_X(0xB4, "LDY", AddressingMode.ZERO_PAGE_X),
    LDA_ZERO_PAGE_X(0xB5, "LDA", AddressingMode.ZERO_PAGE_X),
    LDX_ZERO_PAGE_Y(0xB6, "LDX", AddressingMode.ZERO_PAGE_Y),
    LAX_ZERO_PAGE_Y(0xB7, "LAX", AddressingMode.ZERO_PAGE_Y),
    CLV(0xB8, "CLV", AddressingMode.IMPLIED),
    LDA_ABSOLUTE_Y(0xB9, "LDA", AddressingMode.ABSOLUTE_Y),
    TSX(0xBA, "TSX", AddressingMode.IMPLIED),
    LAS_ABSOLUTE_Y(0xBB, "LAS", AddressingMode.ABSOLUTE_Y),
    LDY_ABSOLUTE_X(0xBC, "LDY", AddressingMode.ABSOLUTE_X),
    LDA_ABSOLUTE_X(0xBD, "LDA", AddressingMode.ABSOLUTE_X),
    LDX_ABSOLUTE_Y(0xBE, "LDX", AddressingMode.ABSOLUTE_Y),
    LAX_ABSOLUTE_Y(0xBF, "LAX", AddressingMode.ABSOLUTE_Y),

    CPY_IMMEDIATE(0xC0, "CPY", AddressingMode.IMMEDIATE),
    CMP_INDIRECT_X(0xC1, "CMP", AddressingMode.INDIRECT_X),
    NOP_IMMEDIATE_C2(0xC2, "NOP", AddressingMode.IMMEDIATE),
    DCP_INDIRECT_X(0xC3, "DCP", AddressingMode.INDIRECT_X),
    CPY_ZERO_PAGE(0xC4, "CPY", AddressingMode.ZERO_PAGE),
    CMP_ZERO_PAGE(0xC5, "CMP", AddressingMode.ZERO_PAGE),
    DEC_ZERO_PAGE(0xC6, "DEC", AddressingMode.ZERO_PAGE),
    DCP_ZERO_PAGE(0xC7, "DCP", AddressingMode.ZERO_PAGE),
    INY(0xC8, "INY", AddressingMode.IMPLIED),
    CMP_IMMEDIATE(0xC9, "CMP", AddressingMode.IMMEDIATE),
    DEX(0xCA, "DEX", AddressingMode.IMPLIED),
    AXS_IMMEDIATE(0xCB, "AXS", AddressingMode.IMMEDIATE),
    CPY_ABSOLUTE(0xCC, "CPU", AddressingMode.ABSOLUTE),
    CMP_ABSOLUTE(0xCD, "CMP", AddressingMode.ABSOLUTE),
    DEC_ABSOLUTE(0xCE, "DEC", AddressingMode.ABSOLUTE),
    DCP_ABSOLUTE(0xCF, "DCP", AddressingMode.ABSOLUTE),

    BNE(0xD0, "BNE", AddressingMode.RELATIVE),
    CMP_INDIRECT_Y(0xD1, "CMP", AddressingMode.INDIRECT_Y),
    STP_D2(0xD2, "STP", AddressingMode.IMPLIED),
    DCP_INDIRECT_Y(0xD3, "DCP", AddressingMode.INDIRECT_Y),
    NOP_ZERO_PAGE_X_D4(0xD4, "NOP", AddressingMode.ZERO_PAGE_X),
    CMP_ZERO_PAGE_X(0xD5, "CMP", AddressingMode.ZERO_PAGE_X),
    DEC_ZERO_PAGE_X(0xD6, "DEC", AddressingMode.ZERO_PAGE_X),
    DCP_ZERO_PAGE_X(0xD7, "DCP", AddressingMode.ZERO_PAGE_X),
    CLD(0xD8, "CLD", AddressingMode.IMPLIED),
    CMP_ABSOLUTE_Y(0xD9, "CMP", AddressingMode.ABSOLUTE_Y),
    NOP_DA(0xDA, "NOP", AddressingMode.IMPLIED),
    DCP_ABSOLUTE_Y(0xDB, "DCP", AddressingMode.ABSOLUTE_Y),
    NOP_ABSOLUTE_X_DC(0xDC, "NOP", AddressingMode.ABSOLUTE_X),
    CMP_ABSOLUTE_X(0xDD, "CMP", AddressingMode.ABSOLUTE_X),
    DEC_ABSOLUTE_X(0xDE, "DEC", AddressingMode.ABSOLUTE_X),
    DCP_ABSOLUTE_X(0xDF, "DCP", AddressingMode.ABSOLUTE_X),

    CPX_IMMEDIATE(0xE0, "CPX", AddressingMode.IMMEDIATE),
    SBC_INDIRECT_X(0xE1, "SBC", AddressingMode.INDIRECT_X),
    NOP_IMMEDIATE_E2(0xE2, "NOP", AddressingMode.IMMEDIATE),
    ISC_INDIRECT_X(0xE3, "ISC", AddressingMode.INDIRECT_X),
    CPX_ZERO_PAGE(0xE4, "CPX", AddressingMode.ZERO_PAGE),
    SBC_ZERO_PAGE(0xE5, "SBC", AddressingMode.ZERO_PAGE),
    INC_ZERO_PAGE(0xE6, "INC", AddressingMode.ZERO_PAGE),
    ISC_ZERO_PAGE(0xE7, "ISC", AddressingMode.ZERO_PAGE),
    INX(0xE8, "INX", AddressingMode.IMPLIED),
    SBC_IMMEDIATE_E9(0xE9, "SBC", AddressingMode.IMMEDIATE),
    NOP_EA(0xEA, "NOP", AddressingMode.IMPLIED),
    SBC_IMMEDIATE_EB(0xEB, "SBC", AddressingMode.IMMEDIATE),
    CPX_ABSOLUTE(0xEC, "CPX", AddressingMode.ABSOLUTE),
    SBC_ABSOLUTE(0xED, "SBC", AddressingMode.ABSOLUTE),
    INC_ABSOLUTE(0xEE, "INC", AddressingMode.ABSOLUTE),
    ISC_ABSOLUTE(0xEF, "ISC", AddressingMode.ABSOLUTE),

    BEQ(0xF0, "BEQ", AddressingMode.RELATIVE),
    SBC_INDIRECT_Y(0xF1, "SBC", AddressingMode.INDIRECT_Y),
    STP_F2(0xF2, "STP", AddressingMode.IMPLIED),
    ISC_INDIRECT_Y(0xF3, "ISC", AddressingMode.INDIRECT_Y),
    NOP_ZERO_PAGE_X_F4(0xF4, "NOP", AddressingMode.ZERO_PAGE_X),
    SBC_ZERO_PAGE_X(0xF5, "SBC", AddressingMode.ZERO_PAGE_X),
    INC_ZERO_PAGE_X(0xF6, "INC", AddressingMode.ZERO_PAGE_X),
    ISC_ZERO_PAGE_X(0xF7, "ISC", AddressingMode.ZERO_PAGE_X),
    SED(0xF8, "SED", AddressingMode.IMPLIED),
    SBC_ABSOLUTE_Y(0xF9, "SBC", AddressingMode.ABSOLUTE_Y),
    NOP_FA(0xFA, "NOP", AddressingMode.IMPLIED),
    ISC_ABSOLUTE_Y(0xFB, "ISC", AddressingMode.ABSOLUTE_Y),
    NOP_ABSOLUTE_X_FC(0xFC, "NOP", AddressingMode.ABSOLUTE_X),
    SBC_ABSOLUTE_X(0xFD, "SBC", AddressingMode.ABSOLUTE_X),
    INC_ABSOLUTE_X(0xFE, "INC", AddressingMode.ABSOLUTE_X),
    ISC_ABSOLUTE_X(0xFF, "ISC", AddressingMode.ABSOLUTE_X);

    private static final HashMap<Integer, Opcode> enumMap = new HashMap<>();

    static {
        for (Opcode op : Opcode.values()) {
            enumMap.put(op.value, op);
        }
    }

    private final int value;
    private final String name;
    private final AddressingMode addressingMode;

    Opcode(int value, String name, AddressingMode addressingMode) {
        this.value = value;
        this.name = name;
        this.addressingMode = addressingMode;
    }

    public static Opcode fromCode(int opcode) {
        return enumMap.get(opcode);
    }

    public String getName() {
        return name;
    }

    public AddressingMode getAddressingMode() {
        return addressingMode;
    }
}
